export const Alias = {
  Secret: {
    GENERATE: 'BACKGROUND_GENERATE_SECRET',
  },
  Auth: {
    STORE_TOKEN: 'BACKGROUND_STORE_TOKEN',
    CLEAR_TOKEN: 'BACKGROUND_CLEAR_TOKEN',
    PING_FOR_TOKEN: 'BACKGROUND_PING_FOR_TOKEN',
    PONG_FOR_TOKEN: 'BACKGROUND_PONG_FOR_TOKEN',
  },
  Invoker: {
    INVOKE: 'BACKGROUND_INVOKE',
  }
} as const;
